build:
    environment:
        php: '8.0.19'
        node: '14.0'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
