services:

    # Tempo runs as user 10001, and docker compose creates the volume as root.
    # As such, we need to chown the volume in order for Tempo to start correctly.
    init:
        image: &tempoImage grafana/tempo:main-1a21818
        user: root
        entrypoint:
            - "chown"
            - "10001:10001"
            - "/var/tempo"
        volumes:
            - ./tempo-data:/var/tempo

    tempo:
        image: *tempoImage
        command: [ "-config.file=/etc/tempo.yaml" ]
        volumes:
            - ./otel/grafana/tempo.yaml:/etc/tempo.yaml
            - ./tempo-data:/var/tempo
        networks:
            otel:
            spryker_private:
            spryker_public:

        ports:
            - "14268"  # jaeger ingest
            - "3200"   # tempo
            - "4317"  # otlp grpc
            - "4318"  # otlp http
            - "9411"   # zipkin
        depends_on:
            - init

    # And put them in an OTEL collector pipeline...
    collector:
        image: otel/opentelemetry-collector:0.86.0
        command: [ "--config=/etc/otel-collector.yaml" ]
        volumes:
            - ./otel/otel-collector/otel-collector.yaml:/etc/otel-collector.yaml

        networks:
            otel:
            spryker_private:
            spryker_public:

    prometheus:
        image: prom/prometheus:latest
        command:
            - --config.file=/etc/prometheus.yaml
            - --web.enable-remote-write-receiver
            - --enable-feature=exemplar-storage
        networks:
            otel:
        volumes:
            - ./otel/grafana/prometheus.yaml:/etc/prometheus.yaml
        ports:
            - "9090:9090"

    grafana:
        image: grafana/grafana:11.0.0
        volumes:
            - ./otel/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
        networks:
            otel:
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor

        ports:
            - "3000:3000"

networks:
    otel:
    spryker_private:
        external: true
    spryker_public:
        external: true
