name: B2C-MP-CI

on:
    pull_request:
        types: [ labeled, unlabeled, synchronize ]
    push:
        branches:
            - feature/cc-33509/cc-3573-smart-slack-pipeline-failure-notifications-v2-testing
    workflow_dispatch:

env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    WEEKLY_CI_SLACK_CHANNEL_ID: ${{ secrets.WEEKLY_CI_SLACK_CHANNEL_ID }}

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    js-validation:
        if: >
            github.ref == 'refs/heads/feature/cc-33509/cc-3573-smart-slack-pipeline-failure-notifications-v2-testing'
        name: "NPM validation"
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false

        env:
            APPLICATION_ENV: ci.mysql
            PROJECT: suite

        steps:
            -   uses: actions/checkout@v4

            -   name: Front-end MP Unit Tests
                run: exit 1

            -   name: Slack Notification for failed job
                uses: ./.github/actions/job-slack-notifications
                if: always()