name: CI for pull requests
on:
  pull_request:
    branches:
      - master

env:
  APPLICATION_ENV: ci
  SPRYKER_TESTING_ENABLED: 1
  APPLICATION_STORE: DE
  POSTGRES_PORT: 5433
  POSTGRES_USER: postgres
  POSTGRES_DB: DE_test_zed
  DB_PASSWORD: secret

jobs:
  unit-tests:
    name: 'Check code style'
    runs-on: ubuntu-20.04
    services:
      database:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: redis
          ini-values: memory_limit=-1
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: 'Prepare file system'
        run: ./config/Shared/ci/ga/prepare_file_system.sh
      - name: 'Install project'
        run: vendor/bin/install DE -r ci -x fixtures
      - name: 'Run tests'
        run: vendor/bin/codecept run -c codeception.ci.functional.yml

